### ISSUE TITLE
Bugnet is unusable

### ISSUE THREAD

**Issue by Tailsa** [dubeaud/bugnet#193]
For the second time in a week the system has become almost totally unusable 
If you try to edit a project or the users list you are presented with an application error:
"Application Error - /BugNet/Administration/Users/UserList
An error has occured in processing your request.
Please try again."

Last week we tried restarting IIS and then ended up rolling the database back.  That was a harsh option but our only way to get back in business.  We are having the same problem today - please help!!

**Comment by dubeaud** [comment]
Can you access the error log any other information you can provide on how to reproduce? Thanks.

**Comment by Tailsa** [comment]
OFFICIAL USE ONLY / À USAGE EXCLUSIF

Hi Dave - so glad to hear from you! 

The error log within the app viewer (Log Viewer) is always empty 

Is there an error log location within the directory structure? 

 

I cannot imagine how to reproduce this issue, the users are simply adding new issues to existing projects.

 

I'll try anything to get this resolved! 

 

-Ailsa

**Comment by dubeaud** [comment]
The log should have captured something, but it may have created a log4net.log in the root directory of the system if something created an error at a deeper level as a fallback.  You can turn friendly errors off , and then get your users to contact you when they get the yellow screen of death with the details also.

I assume you are using the latest version?

**Comment by Tailsa** [comment]
OFFICIAL USE ONLY / À USAGE EXCLUSIF

Hi Dave 

 

We have no log4net.log file - only a log4net.config file 

(Attached) 

 

This is the only error message given 

 

 

 

 

It really seems to be every action under /bugnet/administration

 

-Ailsa

**Comment by Tailsa** [comment]
Update - the problem seems to be caused by duplicate username in the user list
this is a snippet from the event viewer of the server 
Exception information: 
    Exception type: ArgumentException 
    Exception message: Item has already been added. Key in dictionary: 'XXXX\lackiej'  Key being added: 'XXXX\lackiej'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Web.Security.MembershipUserCollection.Add(MembershipUser user)
   at System.Web.Providers.DefaultMembershipProvider.GetAllUsers(Int32 pageIndex, Int32 pageSize, Int32& totalRecords)
   at BugNET.Providers.MembershipProviders.ExtendedSqlMembershipProvider.GetAllUsers(Int32 pageIndex, Int32 pageSize, Int32& totalRecords)
   at BugNET.Administration.Projects.UserControls.ProjectDescription.Initialize()
   at BugNET.Administration.Projects.EditProject.LoadTab(Int32 selectedTab)
   at BugNET.Administration.Projects.EditProject.Page_Load(Object sender, EventArgs e)
   at BugNET.UserInterfaceLayer.BasePage.OnLoad(EventArgs e)
   at System.Web.UI.Control.<LoadRecursiveAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__14.MoveNext()


We checked the database and there are two entries for the same username lackiej
Authentication is done to our AD server, users are created in BugNet the first time they browse, they are queried against our AD server.   
How to prevent this problem from occurring? 
How to correct this problem without rolling back the database

**Comment by dubeaud** [comment]
Other users have reported this issue as well. Not that it helps your immediate need.  

https://github.com/dubeaud/bugnet/issues/125

**Comment by Tailsa** [comment]
Update from our DBA:
The IDX_UserName exists.  It is Non-Unique, which is why there are 2 XXXX\lackiej entries. 
 Should it be unique?  If yes, I would have to drop this index and recreate it.  But the row with the duplicate UserName has to be removed first.  Can it be deleted manually?

**Comment by dubeaud** [comment]
Yes, it should be unique.  You can try to delete it manually, it may fail on a foreign key if the user has created any related data.

**Comment by Tailsa** [comment]
We decided to delete both entries for the user lackiej and this has allowed us to regain control of the system -For now
How do we prevent this problem from occurring again?   It seems there is an expectation from the app that the user name is unique but that part of the database is not written that way?

**Comment by dubeaud** [comment]
I think a unique constraint is in order on that database column.
