### ISSUE TITLE
Gravatar causes error when user has no email address

### ISSUE THREAD

**Issue by efficiondave** [dubeaud/bugnet#53]
If the user doesn't have an email address (which can happen with Active Directory integration), and Gravatar is enabled. You get an error when the user tries to login. It should handle that more gracefully. From the error logs, here's the error:

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BugNET.UserInterfaceLayer.PresentationUtils.GetGravatarImageUrl(String email, Int32 imgSize)
   at BugNET.SiteMaster.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at ASP.default_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\d53d39c0\869f3e6c\App_Web_default.aspx.cdcab7d2.m6emzxzz.0.cs:line 0
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by dubeaud** [comment]
This was merged already , so closing the issue. Thanks.
