### ISSUE TITLE
Application Error after adding a comment

### ISSUE THREAD

**Issue by asudman** [dubeaud/bugnet#98]
I have users that are getting the following after clicking on the 'Add Comment' button: Application Error - /DssIssues/Issues/IssueDetail.aspx

It is not happening for all for all of them, just some, and I cannot get this to happen for me.

Thanks!
![ticketing tool error](https://cloud.githubusercontent.com/assets/11390831/6563601/67e7ed5a-c670-11e4-8ee9-2cdf708ab95c.PNG)

**Comment by dubeaud** [comment]
Can you check the application log and see if there are any error details there?

**Comment by asudman** [comment]
Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 3/9/2015 4:19:55 PM 
Event time (UTC): 3/9/2015 9:19:55 PM 
Event ID: 34f784f9e60b417386f70e3fc9ee9404 
Event sequence: 580 
Event occurrence: 2 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/DssIssues-1-130704025756226228 
    Trust level: Full 
    Application Virtual Path: /DssIssues 
    Application Path: C:\inetpub\wwwroot\BugNET\ 
    Machine name: US00127702 
 
Process information: 
    Process ID: 900 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\DefaultAppPool 
 
Exception information: 
    Exception type: InvalidOperationException 
    Exception message: There was an error generating the XML document.
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at BugNET.Common.Extensions.ToXml[T](T obj)
   at BugNET.BLL.Notifications.NotificationManager.GenerateNotificationContent(String template, Dictionary`2 data)
   at BugNET.BLL.Notifications.CultureContent.TransformContent(Dictionary`2 data)
   at BugNET.BLL.IssueNotificationManager.SendNewIssueCommentNotification(Int32 issueId, IssueComment newComment)
   at BugNET.BLL.IssueCommentManager.SaveOrUpdate(IssueComment entity)
   at BugNET.Issues.UserControls.Comments.CmdAddCommentClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__14.MoveNext()

'.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String ns, String value)
   at System.Xml.Serialization.XmlSerializationWriter.WriteElementString(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterIssue.Write3_Issue(String n, String ns, Issue o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterIssue.Write4_Issue(Object o)

 
 
Request information: 
    Request URL: http://us00127702/DssIssues/Issues/IssueDetail.aspx?id=2413 
    Request path: /DssIssues/Issues/IssueDetail.aspx 
    User host address: 138.85.223.61 
    User: ebritwi 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: IIS APPPOOL\DefaultAppPool 
 
Thread information: 
    Thread ID: 41 
    Thread account name: IIS APPPOOL\DefaultAppPool 
    Is impersonating: False 
    Stack trace:    at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at BugNET.Common.Extensions.ToXml[T](T obj)
   at BugNET.BLL.Notifications.NotificationManager.GenerateNotificationContent(String template, Dictionary`2 data)
   at BugNET.BLL.Notifications.CultureContent.TransformContent(Dictionary`2 data)
   at BugNET.BLL.IssueNotificationManager.SendNewIssueCommentNotification(Int32 issueId, IssueComment newComment)
   at BugNET.BLL.IssueCommentManager.SaveOrUpdate(IssueComment entity)
   at BugNET.Issues.UserControls.Comments.CmdAddCommentClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__14.MoveNext()
 
 
Custom event details: 




On Monday, March 9, 2015 3:58 PM, Davin Dubeau <notifications@github.com> wrote:
 


Can you check the application log and see if there are any error details there?

**Comment by asudman** [comment]
I will add that these comments are being added to issues that I have created "behind the scenes" with a sql server integrations package, so there could be an element missing from the issue.



On Monday, March 9, 2015 4:40 PM, Andrew Sudman <asudman@yahoo.com> wrote:
 


Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 3/9/2015 4:19:55 PM 
Event time (UTC): 3/9/2015 9:19:55 PM 
Event ID: 34f784f9e60b417386f70e3fc9ee9404 
Event sequence: 580 
Event occurrence: 2 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/DssIssues-1-130704025756226228 
    Trust level: Full 
    Application Virtual Path: /DssIssues 
   
 Application Path: C:\inetpub\wwwroot\BugNET\ 
    Machine name: US00127702 
 
Process information: 
    Process ID: 900 
    Process name: w3wp.exe 
    Account name: IIS APPPOOL\DefaultAppPool 
 
Exception information: 
    Exception type: InvalidOperationException 
    Exception message: There was an error generating the XML document.
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at BugNET.Common.Extensions.ToXml[T](T obj)
   at
 BugNET.BLL.Notifications.NotificationManager.GenerateNotificationContent(String template, Dictionary`2 data)
   at BugNET.BLL.Notifications.CultureContent.TransformContent(Dictionary`2 data)
   at BugNET.BLL.IssueNotificationManager.SendNewIssueCommentNotification(Int32 issueId, IssueComment newComment)
   at BugNET.BLL.IssueCommentManager.SaveOrUpdate(IssueComment entity)
   at BugNET.Issues.UserControls.Comments.CmdAddCommentClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__14.MoveNext()

'.', hexadecimal value 0x00, is an invalid character.
   at
 System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteElementString(String localName, String ns, String value)
   at System.Xml.Serialization.XmlSerializationWriter.WriteElementString(String localName, String ns, String value)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterIssue.Write3_Issue(String n, String ns, Issue o, Boolean isNullable, Boolean needType)
   at
 Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterIssue.Write4_Issue(Object o)

 
 
Request information: 
    Request URL: http://us00127702/DssIssues/Issues/IssueDetail.aspx?id=2413 
    Request path: /DssIssues/Issues/IssueDetail.aspx 
    User host address: 138.85.223.61 
    User: ebritwi 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: IIS APPPOOL\DefaultAppPool 
 
Thread information: 
    Thread ID: 41 
    Thread account name: IIS
 APPPOOL\DefaultAppPool 
    Is impersonating: False 
    Stack trace:    at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at BugNET.Common.Extensions.ToXml[T](T obj)
   at BugNET.BLL.Notifications.NotificationManager.GenerateNotificationContent(String template, Dictionary`2 data)
   at BugNET.BLL.Notifications.CultureContent.TransformContent(Dictionary`2 data)
   at BugNET.BLL.IssueNotificationManager.SendNewIssueCommentNotification(Int32 issueId, IssueComment newComment)
   at BugNET.BLL.IssueCommentManager.SaveOrUpdate(IssueComment entity)
   at
 BugNET.Issues.UserControls.Comments.CmdAddCommentClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__14.MoveNext()
 
 
Custom event details: 




On Monday, March 9, 2015 3:58 PM, Davin Dubeau <notifications@github.com> wrote:
 


Can you check the application log and see if there are any error details there?

**Comment by dubeaud** [comment]
if you are adding them directly to the database then that should be ok, but if you are adding them through the business logic then that may be the problem because the notifications wouldn't expect that.  It looks like the problem is in the notifications.

**Comment by asudman** [comment]
I am creating and adding the issues directly to the database, and then afterwards the users are adding a comment using the BugNet application and that is when the error occurs.  Is there something that I need to add/set when creating those issues?



On Monday, March 9, 2015 5:54 PM, Davin Dubeau <notifications@github.com> wrote:
 


if you are adding them directly to the database then that should be ok, but if you are adding them through the business logic then that may be the problem because the notifications wouldn't expect that.  It looks like the problem is in the notifications.

**Comment by asudman** [comment]
Also, I recently moved the BugNet database from one PC to another.  Is there a switch or setting related to notifications that may need to be changed that could be causing this?



On Tuesday, March 10, 2015 7:55 AM, Andrew Sudman <asudman@yahoo.com> wrote:
 


I am creating and adding the issues directly to the database, and then afterwards the users are adding a comment using the BugNet application and that is when the error occurs.  Is there something that I need to add/set when creating those issues?



On Monday, March 9, 2015 5:54 PM, Davin Dubeau <notifications@github.com> wrote:
 


if you are adding them directly to the database then that should be ok, but if you are adding them through the business logic then that may be the problem because the notifications wouldn't expect that.  It looks like the problem is in the notifications.

**Comment by asudman** [comment]
btw...this works now.  I went into the application configuration>mail settings and just hit 'update settings' and things started to work.  you can close the issue.



On Tuesday, March 10, 2015 9:35 AM, Andrew Sudman <asudman@yahoo.com> wrote:
 


Also, I recently moved the BugNet database from one PC to another.  Is there a switch or setting related to notifications that may need to be changed that could be causing this?



On Tuesday, March 10, 2015 7:55 AM, Andrew Sudman <asudman@yahoo.com> wrote:
 


I am creating and adding the issues directly to the database, and then afterwards the users are adding a comment using the BugNet application and that is when the error occurs.  Is there something that I need to add/set when creating those issues?



On Monday, March 9, 2015 5:54 PM, Davin Dubeau <notifications@github.com> wrote:
 


if you are adding them directly to the database then that should be ok, but if you are adding them through the business logic then that may be the problem because the notifications wouldn't expect that.  It looks like the problem is in the notifications.

**Comment by dubeaud** [comment]
ok great, glad it is working now.
